import Head from 'next/head'
import {BsFillMoonStarsFill ,  BsSunFill , BsTelegram} from "react-icons/bs";
import  {AiFillBehanceCircle , AiFillGithub} from "react-icons/ai";
import Image from "next/image";
import vladmult from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import avatar from "../public/avatar.jpg";
import avatar2 from "../public/avatar2.jpg";

import annabotyk from '../public/annabotyk.png';
import bitnews from '../public/bitnews.png';
import implantolog from "../public/implantolog.png";
import milano from "../public/milano.png";
import exotic_vape from "../public/exotic_vape.png";
import majorik from '../public/majorik.png';
import big_femily from '../public/big_femily.png';
import este_solution from '../public/este_solution.png';
import pomado from '../public/pomado.png';
import daschool from '../public/daschool.png'
import int_finance from '../public/int_finance.png';
import carprotection from '../public/carprotection.png';
import wizardavtocolor from '../public/wizardavtocolor.png';
import hairtalk from '../public/hair.png';
import energytime from '../public/energytime.png';
import salesmarketing from '../public/sales-marketing.com.ua.png';
import {  useState } from 'react';




export default function Home() {
    const [darkMode , setDarkMode] = useState(false);
    const [majorikHoverState , setMajorikHoverState] = useState(false);
    const [implantologHoverState, setImplantologHoverState] = useState(false);
    const [bigFemilyHoverState, setBigFemilyHoverState] = useState(false);
    const [esteSolutionHoverState, setEsteSolutionHoverState] = useState(false);
    const [hairtalkHoverState, setHairtalkHoverState] = useState(false);
    const [energyTimeHoverState, setEnergyTimeHoverState] = useState(false);
    const [milanoHoverState, setMilanoHoverState] = useState(false);
    const [exoticVapeHoverState, setExoticVapeHoverState] = useState(false);
    const [annaBotykHoverState, setAnnaBotykHoverState] = useState(false);
    const [salesMarketingHoverState, setsalesMarketingkHoverState] = useState(false);
    const [bitNewsHoverState, setBitNewsHoverState] = useState(false);
    const [langState , setLangState] = useState(true);

    /* eslint-disable */
    return (
        <div className={ darkMode ? 'dark text-white' : ''}>
            <Head>
                <title>Vladyslav Darahan Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/vlad.jpg"  />
                <meta name='freelancehunt' content='98534fe17c3c8ea' />
            </Head>

            <main className={'bg-white px-5 md:px-20 lg:px-40 dark:bg-slate-900'}>
                <section className={'min-h-screen'}>
                    <nav className={"py-10 mb-12 flex justify-between "}>

                        <h1 className={'text-xl font-burtons uppercase  mr-2 dark:text-white'}>'Vladyslav Dar'</h1>
                        <ul className={'flex items-center'}>
                            <li>{darkMode ? <BsFillMoonStarsFill className={'cursor-pointer text-2xl fill-white'} onClick={() => setDarkMode(false)} ></BsFillMoonStarsFill> : <BsSunFill  onClick={() => setDarkMode(true)} className={'cursor-pointer text-2xl'}/>}</li>
                            <li><div className={'lang-box hover:shadow-2xl  bg-gradient-to-r from-cyan-500 to-teal-500' +
                                ' text-white' +
                                ' rounded-md' +
                                ' ml-8 dark:hover:shadow-black  dark:shadow-xl flex items-center flex-row-reverse'}><span className={!langState ? 'cursor-pointer rounded-md' : 'cursor-pointer span--active rounded-md'} onClick={() => setLangState(false)}>En</span>
                                <div className={'line-lang'}></div> <span className={ !langState ? 'cursor-pointer span--active rounded-md' : 'cursor-pointer rounded-md'}  onClick={() => setLangState(true)}>Ua</span></div></li>
                        </ul>
                    </nav>
                    <div className={'text-center p-0 lg:p-15 md:p-10 sm:p-10'}>
                        <h2 className={'text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'}>Vladyslav Darahan</h2>
                        <h3 className={'text-2xl py-2 dark:text-white'}>{langState ? 'Веб-розробник і Дизайнер' : 'Web' +
                            ' Developer and Designer' }</h3>
                    </div>
                    <p className={'text-xl  mb-5 font-medium  leading-8 text-teal-500 md:px-10 dark:text-teal-200' +
                        ' text-center mt-10 md:mt-0'}>{langState ? 'Напиши мені' : 'Contact with me'}</p>
                    <div className={'text-5xl flex justify-center gap-8  text-gray-600 dark:text-white'}>
                         <a href={'https://t.me/vla_decr'} target={'_blank'} rel={'noreferrer'} className={'hover:text-gray-300'} ><BsTelegram/></a>
                        <a href={'https://www.behance.net/vladislavdar'} className={'hover:text-gray-300'} target={'_blank'} rel={'noreferrer'}><AiFillBehanceCircle /></a>
                        <a href={'https://github.com/vla-decr000'} target={'_blank'} rel={'noreferrer'} className={'hover:text-gray-300'} ><AiFillGithub/></a>
                    </div>
                    <div className={'relative bg-gradient-to-b  from-teal-500 overflow-hidden rounded-full ' +
                        ' justify-center w-80 h-80 flex' +
                        ' items-center mx-auto my-14'} style={{'maxWidth': '-webkit-fill-available'}}>
                        <Image alt={'img'} src={avatar2} layout={'fill'} objectFit={'cover'}/>
                    </div>
                </section>

                <section>
                    <div>
                        <h3 className={'text-3xl py-1'}>{langState ? 'Послуги , які я пропоную' : 'Services i offer'}</h3>
                        {langState ?<p className={'text-services text-md py-2 leading-7 text-gray-800 dark:text-white'}>
                                Я пропоную вам : створення дизайну  і перетворення його в сайт / створення копії якогось веб-сайту зі змінами  - всі мої послуги можна побачити  <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>нижче .</a>
                                Також подивіться <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>мої прилади </a> і <a className={'text-teal-500 dark:text-teal-300'} href={'#portfolio'}>моє портфоліо</a>  нижче !
                            </p>
                            :
                            <p className={'text-services text-md py-2 leading-7 text-gray-800 dark:text-white'}>
                                I offer for  you: creation design for your web site and make a layout from this design
                                / make a copy of some website with changes  - all my services you can watch  <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>below .</a>
                                Watch my <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>tools</a> and <a className={'text-teal-500 dark:text-teal-300'} href={'#portfolio'}>portfolio</a>  below too !
                            </p>}
                    </div>
                    <div className={'block xl:flex xl:gap-5 '} id={'tools'}>
                        {langState ? <div className={'text-center shadow-lg px-0 py-10 rounded-xl my-10 basis-1/3  dark:bg-white  ,' +
                            ' text-black'}>
                            <Image alt={'img'} src={code}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>Веб-розробка</h3>
                            <p className={'py-2 px-3.5'}>Створення сайтів швидко і достатньо дешево !</p>
                            <h4 className={'py-4 text-teal-600'}>Прилади  , які я використовую</h4>
                            <p className={'text-gray-800 py-1'}>PHP, Laravel, Wordpress</p>
                            <p className={'text-gray-800 py-1'}>HTML , CSS , JS, Jquery</p>
                            <p className={'text-gray-800 py-1'}>Inertia Js, Vue 3</p>
                            <p className={'text-gray-800 py-1'}>MySQL</p>
                        </div> :  <div className={'text-center shadow-lg px-0 py-10 rounded-xl my-10 basis-1/3  dark:bg-white  ,' +
                            ' text-black'}>
                            <Image alt={'img'} src={code}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>Web Development</h3>
                            <p className={'py-2 px-3.5'}>Create website very fast and enough cheap !</p>
                            <h4 className={'py-4 text-teal-600'}>Web development tools i use</h4>
                            <p className={'text-gray-800 py-1'}>PHP, Laravel, Wordpress</p>
                            <p className={'text-gray-800 py-1'}>HTML , CSS , JS, Jquery</p>
                            <p className={'text-gray-800 py-1'}>Inertia Js, Vue 3</p>
                            <p className={'text-gray-800 py-1'}>MySQL</p>
                        </div>}
                        {langState ?  <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                            <Image alt={'img'} src={design}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>UI/UX</h3>
                            <p className={'py-2 px-3.5'}>Створення цікавих дизайнів в одному стилі !</p>
                            <h4 className={'py-4 text-teal-600'}>Прилади  , які я використовую</h4>
                            <p className={'text-gray-800 py-1'}>Figma</p>
                            <p className={'text-gray-800 py-1'}>Pixso</p>
                        </div> :  <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                            <Image alt={'img'} src={design}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>UI/UX</h3>
                            <p className={'py-2 px-3.5'}>Creating interesting design in identical style !</p>
                            <h4 className={'py-4 text-teal-600'}>Design tools i use</h4>
                            <p className={'text-gray-800 py-1'}>Figma</p>
                            <p className={'text-gray-800 py-1'}>Pixso</p>
                        </div>}
                        {langState ?
                            <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                                <Image alt={'img'} src={consulting}  width={100} height={100} className={'mx-auto'} />
                                <h3 className={'text-lg font-medium pt-8 pb-2'}>Інше</h3>
                                <p className={'py-2 px-3.5'}>Я можу допомогти з різними речами</p>
                                <h4 className={'py-4 text-teal-600'}> Щось наприклад ...</h4>
                                <p className={'text-gray-800 py-1'}>Копірайтинг</p>
                                <p className={'text-gray-800 py-1'}>Домен і хостинг</p>
                                <p className={'text-gray-800 py-1'}>Редакція вже існуючого сайту</p>
                            </div> :
                            <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                                <Image src={consulting} alt={'img'}  width={100} height={100} className={'mx-auto'} />
                                <h3 className={'text-lg font-medium pt-8 pb-2'}>Other</h3>
                                <p className={'py-2 px-3.5'}>I can help you with other things</p>
                                <h4 className={'py-4 text-teal-600'}> Something like ...</h4>
                                <p className={'text-gray-800 py-1'}>Copywriting</p>
                                <p className={'text-gray-800 py-1'}>Domain and hosting</p>
                                <p className={'text-gray-800 py-1'}>Edit your an existing site</p>
                            </div>}
                    </div>
                </section>
                <section>
                    <div className={'mb-14 mt-5'}>
                        <h3 className={'text-3xl py-1'} id={'portfolio'}>{langState ? 'Портфоліо' : 'Portfolio'}</h3>
                        {langState ? <p className={'text-services text-md py-2 leading-7 text-gray-800' +
                                ' dark:text-white'}>Я фрілансер з більш ніж 3 років досвіду в <span className={'underline-text'}>
                      Веб-розробці
                  </span>  і <span className={'underline-text'}>веб-дизайні</span> .
                                Я маю різні навики в цих сферах . Отже можу зробити все ,  що вам потрібно . Перегляньте декілька моїх робіт нижче ...
                            </p> :
                            <p className={'text-services text-md py-2 leading-7 text-gray-800 dark:text-white'}>I&apos;m freelancer with more than 3 years of experience in <span className={'underline-text'}>
                      Web development
                  </span>  and <span className={'underline-text'}>design</span> .
                                I have different skills in this spheres . So i can make  everything you want . Watch some my works below...
                            </p>}
                    </div>
                    <h3 className={'text-4xl py-1 fz- text-center'} id={'portfolio'}>{langState ? 'Перегляньте зараз' : 'Watch now'}</h3>


                     <div className={'flex  flex-col  gap-10 py-10 lg:flex-row lg:flex-wrap justify-center'} >

          <div className={'web__item rounded-lg basis-1/3 shadow-lg flex-1 bg-transparent relative '}onMouseOver={() => setMajorikHoverState(true)} onMouseOut={() => setMajorikHoverState(false)}>
                            {majorikHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://majorik.com'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={majorik} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
          <div className={'web__item rounded-lg basis-1/3 shadow-lg flex-1 bg-transparent relative '}onMouseOver={() => setBitNewsHoverState(true)} onMouseOut={() => setBitNewsHoverState(false)}>
                            {bitNewsHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://bitinsider.io'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={bitnews} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
          <div className={'web__item rounded-lg basis-1/3 shadow-lg flex-1 bg-transparent relative '}onMouseOver={() => setsalesMarketingkHoverState(true)} onMouseOut={() => setsalesMarketingkHoverState(false)}>
                            {salesMarketingHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://sales-marketing.com.ua'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div className={'h-full'}><Image alt={'img'} src={salesmarketing} className={' rounded-t-lg object-cover h-full '} width={'100%'} height={'100%'}  /> </div>
                        </div>

              
                                                                                             
                     <div className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}onMouseOver={() => setMilanoHoverState(true)} onMouseOut={() => setMilanoHoverState(false)}>
                            {milanoHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://milano-group.shop/'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={milano} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
                     <div className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}onMouseOver={() => setImplantologHoverState(true)} onMouseOut={() => setImplantologHoverState(false)}>
                            {implantologHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://implantolog.com.ua/'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={implantolog} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
      
                     <div className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}onMouseOver={() => setAnnaBotykHoverState(true)} onMouseOut={() => setAnnaBotykHoverState(false)}>
                            {annaBotykHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://www.annabotyk.com/'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={annabotyk} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
                     <div className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}onMouseOver={() => setBigFemilyHoverState(true)} onMouseOut={() => setBigFemilyHoverState(false)}>
                            {bigFemilyHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://big-femily.com.ua/'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={big_femily} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
                     <div className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}onMouseOver={() => setEsteSolutionHoverState(true)} onMouseOut={() => setEsteSolutionHoverState(false)}>
                            {esteSolutionHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://www.estesolution.com.ua/'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={este_solution} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
                     <div className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}onMouseOver={() => setHairtalkHoverState(true)} onMouseOut={() => setHairtalkHoverState(false)}>
                            {hairtalkHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'http://www.hairtalkcyprus.com/'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={hairtalk} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
                      
                                            </div>

                                            <h3 className={'text-4xl py-1 fz- text-center'} id={'portfolio'}>{langState ? 'Сайти компаній, що припинили існування' : 'Websites of companies that work no more'}</h3>

                                            <div className={'flex  flex-col  gap-10 py-10 lg:flex-row lg:flex-wrap justify-center'} >

                                            <article className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}>
                                                <div><Image alt={'img'} src={pomado} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                                            </article>
                                            <article className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}>
                                                <div><Image alt={'img'} src={exotic_vape} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                                            </article>
                                            
                                            <article className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}>
                                                <div><Image alt={'img'} src={daschool} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                                            </article>
                                            <article className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}>
                                                <div><Image alt={'img'} src={int_finance} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                                            </article>
                                            <article className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}>
                                                <div><Image alt={'img'} src={carprotection} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                                            </article>
                                            <article className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}>
                                                <div><Image alt={'img'} src={wizardavtocolor} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                                            </article>
                                            <article className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}>
                                                <div><Image alt={'img'} src={energytime} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                                            </article>
                                                
                                            </div>       
                </section>

                <section className='contacts mb-20 mt-4'>
                <p className={'text-3xl  mb-5 font-medium  leading-8 text-teal-500 md:px-10 dark:text-teal-200' +
                        ' text-center mt-10 md:mt-0'}>{langState ? 'Контакти':  'Contacts'}</p>
                    <div className={'text-5xl flex justify-center gap-8  text-gray-600 dark:text-white'}>
                    <a href={'https://t.me/vla_decr'} target={'_blank'} rel={'noreferrer'} className={'hover:text-gray-300'} ><BsTelegram/></a>
                        <a href={'https://www.behance.net/vladislavdar'} className={'hover:text-gray-300'} target={'_blank'} rel={'noreferrer'}><AiFillBehanceCircle /></a>
                        <a href={'https://github.com/vla-decr000'} target={'_blank'} rel={'noreferrer'} className={'hover:text-gray-300'} ><AiFillGithub/></a>
                    </div>
                    <a href='tel:+380668628065' className={'text-2xl block  mb-5 font-medium mt-10  leading-8 text-teal-500 md:px-10 dark:text-teal-200  text-center'}>+38(066)8628065</a>
                </section>
            </main>
            <footer className={'footer   bg-gray-900 text-teal-400 flex items-center justify-center shadow-2xl' +
                '  dark:bg-gradient-to-r' +
                ' from-cyan-500 to-teal-500' +
                ' dark:text-gray-800'}>
                <span>{langState ? 'Дякую за перегляд !' : 'Thank you for watching !'}</span>
            </footer>
        </div>
    );
}
