import Head from 'next/head'
import {BsFillMoonStarsFill ,  BsSunFill , BsTelegram} from "react-icons/bs";
import  {AiFillBehanceCircle , AiFillGithub} from "react-icons/ai";
import Image from "next/image";
import vladmult from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web-1.png';
import web2 from '../public/pomado.png';
import web3 from '../public/web-3.png';
import web4 from '../public/web-4.png';
import web5 from '../public/web-5.png'
import majorik from '../public/majorik.png';
import { useState } from 'react';
export default function Home() {
    const [darkMode , setDarkMode] = useState(false);
    const [majorikHoverState , setMajorikHoverState] = useState(false);
    const [hoverState , setHoverState] = useState(false);
    const [hoverState2 , setHoverState2] = useState(false);
    const [hoverState3 , setHoverState3] = useState(false);
    const [hoverState4 , setHoverState4] = useState(false);
    const [hoverState5 , setHoverState5] = useState(false);
    const [langState , setLangState] = useState(false);
    /* eslint-disable */
    return (
        <div className={ darkMode ? 'dark text-white' : ''}>
            <Head>
                <title>Vladyslav Dar Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/vlad.jpg"  />
                <meta name='freelancehunt' content='98534fe17c3c8ea' />
            </Head>

            <main className={'bg-white px-5 md:px-20 lg:px-40 dark:bg-slate-900'}>
                <section className={'min-h-screen'}>
                    <nav className={"py-10 mb-12 flex justify-between "}>

                        <h1 className={'text-xl font-burtons uppercase  mr-2 dark:text-white'}>'Vladyslav Dar'</h1>
                        <ul className={'flex items-center'}>
                            <li>{darkMode ? <BsFillMoonStarsFill className={'cursor-pointer text-2xl fill-white'} onClick={() => setDarkMode(false)} ></BsFillMoonStarsFill> : <BsSunFill  onClick={() => setDarkMode(true)} className={'cursor-pointer text-2xl'}/>}</li>
                            <li><div className={'lang-box hover:shadow-2xl  bg-gradient-to-r from-cyan-500 to-teal-500' +
                                ' text-white' +
                                ' rounded-md' +
                                ' ml-8 dark:hover:shadow-black  dark:shadow-xl flex items-center'}><span className={!langState ? 'cursor-pointer' : 'cursor-pointer span--active'} onClick={() => setLangState(false)}>En</span>
                                <div className={'line-lang'}></div> <span className={!langState ? 'cursor-pointer span--active' : 'cursor-pointer'}  onClick={() => setLangState(true)}>Ua</span></div></li>
                        </ul>
                    </nav>
                    <div className={'text-center p-0 lg:p-15 md:p-10 sm:p-10'}>
                        <h2 className={'text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'}>Vladyslav Dar</h2>
                        <h3 className={'text-2xl py-2 dark:text-white'}>{langState ? 'Веб-розробник і Дизайнер' : 'Web' +
                            ' Developer and Designer' }</h3>
                    </div>
                    <p className={'text-xl  mb-5 font-medium  leading-8 text-teal-500 md:px-10 dark:text-teal-200' +
                        ' text-center mt-10 md:mt-0'}>{langState ? 'Напиши мені' : 'Contact with me'}</p>
                    <div className={'text-5xl flex justify-center gap-8  text-gray-600 dark:text-white'}>
                        <a href={'https://www.behance.net/vladislavdar'} className={'hover:text-gray-300'} target={'_blank'} rel={'noreferrer'}><AiFillBehanceCircle /></a>
                        <a href={'https://github.com/vla-decr000'} target={'_blank'} rel={'noreferrer'} className={'hover:text-gray-300'} ><AiFillGithub/></a>
                        <a href={'https://t.me/vla_decr'} target={'_blank'} rel={'noreferrer'} className={'hover:text-gray-300'} ><BsTelegram/></a>
                    </div>
                    <div className={'relative bg-gradient-to-b  from-teal-500 overflow-hidden rounded-full ' +
                        ' justify-center w-80 h-80 flex' +
                        ' items-center mx-auto my-14'} style={{'maxWidth': '-webkit-fill-available'}}>
                        <Image alt={'img'} src={vladmult} layout={'fill'} objectFit={'cover'}/>
                    </div>
                </section>

                <section>
                    <div>
                        <h3 className={'text-3xl py-1'}>{langState ? 'Послуги , які я пропоную' : 'Services i offer'}</h3>
                        {langState ?<p className={'text-services text-md py-2 leading-7 text-gray-800 dark:text-white'}>
                                Я пропоную вам : створення дизайну  і перетворення його в сайт / створення копії якогось веб-сайту зі змінами  - всі мої послуги можна побачити  <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>нижче .</a>
                                Також подивіться <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>мої прилади </a> і <a className={'text-teal-500 dark:text-teal-300'} href={'#portfolio'}>моє портфоліо</a>  нижче !
                            </p>
                            :
                            <p className={'text-services text-md py-2 leading-7 text-gray-800 dark:text-white'}>
                                I offer for  you: creation design for your web site and make a layout from this design
                                / make a copy of some website with changes  - all my services you can watch  <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>below .</a>
                                Watch my <a className={'text-teal-500 dark:text-teal-300'} href={'#tools'}>tools</a> and <a className={'text-teal-500 dark:text-teal-300'} href={'#portfolio'}>portfolio</a>  below too !
                            </p>}
                    </div>
                    <div className={'block xl:flex xl:gap-5 '} id={'tools'}>
                        {langState ? <div className={'text-center shadow-lg px-0 py-10 rounded-xl my-10 basis-1/3  dark:bg-white  ,' +
                            ' text-black'}>
                            <Image alt={'img'} src={code}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>Веб-розробка</h3>
                            <p className={'py-2 px-3.5'}>Створення сайтів швидко і достатньо дешево !</p>
                            <h4 className={'py-4 text-teal-600'}>Прилади  , які я використовую</h4>
                            <p className={'text-gray-800 py-1'}>HTML , CSS , JS, Jquery</p>
                            <p className={'text-gray-800 py-1'}>PHP, Laravel</p>
                            <p className={'text-gray-800 py-1'}>React Ts  , Next Ts</p>
                        </div> :  <div className={'text-center shadow-lg px-0 py-10 rounded-xl my-10 basis-1/3  dark:bg-white  ,' +
                            ' text-black'}>
                            <Image alt={'img'} src={code}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>Web Development</h3>
                            <p className={'py-2 px-3.5'}>Create website very fast and enough cheap !</p>
                            <h4 className={'py-4 text-teal-600'}>Web development tools i use</h4>
                            <p className={'text-gray-800 py-1'}>HTML , CSS , JS, Jquery</p>
                            <p className={'text-gray-800 py-1'}>PHP, Laravel</p>
                            <p className={'text-gray-800 py-1'}>React Ts  , Next Ts</p>
                        </div>}
                        {langState ?  <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                            <Image alt={'img'} src={design}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>UI/UX</h3>
                            <p className={'py-2 px-3.5'}>Створення цікавих дизайнів в одному стилі !</p>
                            <h4 className={'py-4 text-teal-600'}>Прилади  , які я використовую</h4>
                            <p className={'text-gray-800 py-1'}>Figma</p>
                        </div> :  <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                            <Image alt={'img'} src={design}  width={100} height={100} className={'mx-auto'} />
                            <h3 className={'text-lg font-medium pt-8 pb-2'}>UI/UX</h3>
                            <p className={'py-2 px-3.5'}>Creating interesting design in identical style !</p>
                            <h4 className={'py-4 text-teal-600'}>Design tools i use</h4>
                            <p className={'text-gray-800 py-1'}>Figma</p>
                        </div>}
                        {langState ?
                            <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                                <Image alt={'img'} src={consulting}  width={100} height={100} className={'mx-auto'} />
                                <h3 className={'text-lg font-medium pt-8 pb-2'}>Інше</h3>
                                <p className={'py-2 px-3.5'}>Я можу допомогти з різними речами</p>
                                <h4 className={'py-4 text-teal-600'}> Щось наприклад ...</h4>
                                <p className={'text-gray-800 py-1'}>Копірайтинг</p>
                                <p className={'text-gray-800 py-1'}>Домен і хостинг</p>
                                <p className={'text-gray-800 py-1'}>Редакція вже існуючого сайту</p>
                            </div> :
                            <div className={'text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 dark:bg-white , text-black'}>
                                <Image src={consulting} alt={'img'}  width={100} height={100} className={'mx-auto'} />
                                <h3 className={'text-lg font-medium pt-8 pb-2'}>Other</h3>
                                <p className={'py-2 px-3.5'}>I can help you with other things</p>
                                <h4 className={'py-4 text-teal-600'}> Something like ...</h4>
                                <p className={'text-gray-800 py-1'}>Copywriting</p>
                                <p className={'text-gray-800 py-1'}>Domain and hosting</p>
                                <p className={'text-gray-800 py-1'}>Edit your an existing site</p>
                            </div>}
                    </div>
                </section>
                <section>
                    <div className={'mb-14 mt-5'}>
                        <h3 className={'text-3xl py-1'} id={'portfolio'}>{langState ? 'Портфоліо' : 'Portfolio'}</h3>
                        {langState ? <p className={'text-services text-md py-2 leading-7 text-gray-800' +
                                ' dark:text-white'}>Я фрілансер з більш ніж 2 років досвіду в <span className={'underline-text'}>
                      Веб-розробці
                  </span>  і <span className={'underline-text'}>веб-дизайні</span> .
                                Я маю різні навики в цих сферах . Отже можу зробити все ,  що вам потрібно . Перегляньте декілька моїх робіт нижче ...
                            </p> :
                            <p className={'text-services text-md py-2 leading-7 text-gray-800 dark:text-white'}>I&apos;m freelancer with more than 2 years of experience in <span className={'underline-text'}>
                      Web development
                  </span>  and <span className={'underline-text'}>design</span> .
                                I have different skills in this spheres . So i can make  everything you want . Watch some my works below...
                            </p>}
                    </div>
                     <div className={'flex  flex-col  gap-10 py-10 lg:flex-row lg:flex-wrap justify-center'} >

          <div className={'web__item rounded-lg basis-1/3 shadow-lg flex-1 bg-transparent relative '}onMouseOver={() => setMajorikHoverState(true)} onMouseOut={() => setMajorikHoverState(false)}>
                            {majorikHoverState ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://majorik.com'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={majorik} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>

                                                                            
                     <div className={'web__item  basis-1/3 shadow-lg flex-1 bg-transparent relative rounded-lg '}onMouseOver={() => setHoverState2(true)} onMouseOut={() => setHoverState2(false)}>
                            {hoverState2 ?   <a className={'item__link rounded-lg  inset-0 absolute  z-100 text-white flex' +
                                ' justify-center' +
                                ' items-center'} href={'https://pomado.com.ua/'} target={'_blank'} rel={'noreferrer'}>
                                <span className={' bg-gradient-to-r from-cyan-500 to-teal-500 '}>{langState ? 'Переглянути':'Watch this'}</span>
                            </a> : ''}
                            <div><Image alt={'img'} src={web2} className={' rounded-t-lg object-cover '} width={'100%'} height={'100%'}  /> </div>
                        </div>
                 
 
                   
                       
                       
                      
                      
                                            </div>
                </section>
            </main>
            <footer className={'footer   bg-gray-900 text-teal-400 flex items-center justify-center shadow-2xl' +
                '  dark:bg-gradient-to-r' +
                ' from-cyan-500 to-teal-500' +
                ' dark:text-gray-800'}>
                <span>{langState ? 'Дякую за перегляд !' : 'Thank you for watching !'}</span>
            </footer>
        </div>
    );
}
